# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_auto_20171230_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(),
        ),
    ]
