# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20180104_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_1',
            new_name='after_photo_1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_10',
            new_name='after_photo_2',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_2',
            new_name='before_photo_1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_3',
            new_name='before_photo_2',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_4',
            new_name='more_photo_1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_5',
            new_name='more_photo_2',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_6',
            new_name='more_photo_3',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_7',
            new_name='more_photo_4',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='gallery_photo_8',
            new_name='more_photo_5',
        ),
        migrations.RemoveField(
            model_name='work',
            name='gallery_photo_9',
        ),
        migrations.RemoveField(
            model_name='work',
            name='main_photo',
        ),
    ]
