# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170926_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(choices=[('W', 'Works'), ('S', 'Skills'), ('R', 'Services')], max_length=50),
        ),
    ]
