# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20171229_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='model',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
