# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180103_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slider_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='company',
            name='slider_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
